<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Pionect\Daalder\Models\Country\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            'BD' => [
                'code' => 'BD',
                'continent' => 'AS',
                'iso3' => 'BGD',
                'capital' => 'Dhaka',
                'name' => 'Bangladesh',
                'currency_code' => 'BDT',
            ],
            'BE' => [
                'code' => 'BE',
                'continent' => 'EU',
                'iso3' => 'BEL',
                'capital' => 'Brussels',
                'name' => 'Belgium',
                'currency_code' => 'EUR',
            ],
            'BF' => [
                'code' => 'BF',
                'continent' => 'AF',
                'iso3' => 'BFA',
                'capital' => 'Ouagadougou',
                'name' => 'Burkina Faso',
                'currency_code' => 'XOF',
            ],
            'BG' => [
                'code' => 'BG',
                'continent' => 'EU',
                'iso3' => 'BGR',
                'capital' => 'Sofia',
                'name' => 'Bulgaria',
                'currency_code' => 'BGN',
            ],
            'BA' => [
                'code' => 'BA',
                'continent' => 'EU',
                'iso3' => 'BIH',
                'capital' => 'Sarajevo',
                'name' => 'Bosnia and Herzegovina',
                'currency_code' => 'BAM',
            ],
            'BB' => [
                'code' => 'BB',
                'continent' => 'NA',
                'iso3' => 'BRB',
                'capital' => 'Bridgetown',
                'name' => 'Barbados',
                'currency_code' => 'BBD',
            ],
            'WF' => [
                'code' => 'WF',
                'continent' => 'OC',
                'iso3' => 'WLF',
                'capital' => 'Mata Utu',
                'name' => 'Wallis and Futuna',
                'currency_code' => 'XPF',
            ],
            'BL' => [
                'code' => 'BL',
                'continent' => 'NA',
                'iso3' => 'BLM',
                'capital' => 'Gustavia',
                'name' => 'Saint Barthelemy',
                'currency_code' => 'EUR',
            ],
            'BM' => [
                'code' => 'BM',
                'continent' => 'NA',
                'iso3' => 'BMU',
                'capital' => 'Hamilton',
                'name' => 'Bermuda',
                'currency_code' => 'BMD',
            ],
            'BN' => [
                'code' => 'BN',
                'continent' => 'AS',
                'iso3' => 'BRN',
                'capital' => 'Bandar Seri Begawan',
                'name' => 'Brunei',
                'currency_code' => 'BND',
            ],
            'BO' => [
                'code' => 'BO',
                'continent' => 'SA',
                'iso3' => 'BOL',
                'capital' => 'Sucre',
                'name' => 'Bolivia',
                'currency_code' => 'BOB',
            ],
            'BH' => [
                'code' => 'BH',
                'continent' => 'AS',
                'iso3' => 'BHR',
                'capital' => 'Manama',
                'name' => 'Bahrain',
                'currency_code' => 'BHD',
            ],
            'BI' => [
                'code' => 'BI',
                'continent' => 'AF',
                'iso3' => 'BDI',
                'capital' => 'Bujumbura',
                'name' => 'Burundi',
                'currency_code' => 'BIF',
            ],
            'BJ' => [
                'code' => 'BJ',
                'continent' => 'AF',
                'iso3' => 'BEN',
                'capital' => 'Porto-Novo',
                'name' => 'Benin',
                'currency_code' => 'XOF',
            ],
            'BT' => [
                'code' => 'BT',
                'continent' => 'AS',
                'iso3' => 'BTN',
                'capital' => 'Thimphu',
                'name' => 'Bhutan',
                'currency_code' => 'BTN',
            ],
            'JM' => [
                'code' => 'JM',
                'continent' => 'NA',
                'iso3' => 'JAM',
                'capital' => 'Kingston',
                'name' => 'Jamaica',
                'currency_code' => 'JMD',
            ],
            'BV' => [
                'code' => 'BV',
                'continent' => 'AN',
                'iso3' => 'BVT',
                'capital' => null,
                'name' => 'Bouvet Island',
                'currency_code' => 'NOK',
            ],
            'BW' => [
                'code' => 'BW',
                'continent' => 'AF',
                'iso3' => 'BWA',
                'capital' => 'Gaborone',
                'name' => 'Botswana',
                'currency_code' => 'BWP',
            ],
            'WS' => [
                'code' => 'WS',
                'continent' => 'OC',
                'iso3' => 'WSM',
                'capital' => 'Apia',
                'name' => 'Samoa',
                'currency_code' => 'WST',
            ],
            'BQ' => [
                'code' => 'BQ',
                'continent' => 'NA',
                'iso3' => 'BES',
                'capital' => null,
                'name' => 'Bonaire, Saint Eustatius and Saba ',
                'currency_code' => 'USD',
            ],
            'BR' => [
                'code' => 'BR',
                'continent' => 'SA',
                'iso3' => 'BRA',
                'capital' => 'Brasilia',
                'name' => 'Brazil',
                'currency_code' => 'BRL',
            ],
            'BS' => [
                'code' => 'BS',
                'continent' => 'NA',
                'iso3' => 'BHS',
                'capital' => 'Nassau',
                'name' => 'Bahamas',
                'currency_code' => 'BSD',
            ],
            'JE' => [
                'code' => 'JE',
                'continent' => 'EU',
                'iso3' => 'JEY',
                'capital' => 'Saint Helier',
                'name' => 'Jersey',
                'currency_code' => 'GBP',
            ],
            'BY' => [
                'code' => 'BY',
                'continent' => 'EU',
                'iso3' => 'BLR',
                'capital' => 'Minsk',
                'name' => 'Belarus',
                'currency_code' => 'BYR',
            ],
            'BZ' => [
                'code' => 'BZ',
                'continent' => 'NA',
                'iso3' => 'BLZ',
                'capital' => 'Belmopan',
                'name' => 'Belize',
                'currency_code' => 'BZD',
            ],
            'RU' => [
                'code' => 'RU',
                'continent' => 'EU',
                'iso3' => 'RUS',
                'capital' => 'Moscow',
                'name' => 'Russia',
                'currency_code' => 'RUB',
            ],
            'RW' => [
                'code' => 'RW',
                'continent' => 'AF',
                'iso3' => 'RWA',
                'capital' => 'Kigali',
                'name' => 'Rwanda',
                'currency_code' => 'RWF',
            ],
            'RS' => [
                'code' => 'RS',
                'continent' => 'EU',
                'iso3' => 'SRB',
                'capital' => 'Belgrade',
                'name' => 'Serbia',
                'currency_code' => 'RSD',
            ],
            'TL' => [
                'code' => 'TL',
                'continent' => 'OC',
                'iso3' => 'TLS',
                'capital' => 'Dili',
                'name' => 'East Timor',
                'currency_code' => 'USD',
            ],
            'RE' => [
                'code' => 'RE',
                'continent' => 'AF',
                'iso3' => 'REU',
                'capital' => 'Saint-Denis',
                'name' => 'Reunion',
                'currency_code' => 'EUR',
            ],
            'TM' => [
                'code' => 'TM',
                'continent' => 'AS',
                'iso3' => 'TKM',
                'capital' => 'Ashgabat',
                'name' => 'Turkmenistan',
                'currency_code' => 'TMT',
            ],
            'TJ' => [
                'code' => 'TJ',
                'continent' => 'AS',
                'iso3' => 'TJK',
                'capital' => 'Dushanbe',
                'name' => 'Tajikistan',
                'currency_code' => 'TJS',
            ],
            'RO' => [
                'code' => 'RO',
                'continent' => 'EU',
                'iso3' => 'ROU',
                'capital' => 'Bucharest',
                'name' => 'Romania',
                'currency_code' => 'RON',
            ],
            'TK' => [
                'code' => 'TK',
                'continent' => 'OC',
                'iso3' => 'TKL',
                'capital' => null,
                'name' => 'Tokelau',
                'currency_code' => 'NZD',
            ],
            'GW' => [
                'code' => 'GW',
                'continent' => 'AF',
                'iso3' => 'GNB',
                'capital' => 'Bissau',
                'name' => 'Guinea-Bissau',
                'currency_code' => 'XOF',
            ],
            'GU' => [
                'code' => 'GU',
                'continent' => 'OC',
                'iso3' => 'GUM',
                'capital' => 'Hagatna',
                'name' => 'Guam',
                'currency_code' => 'USD',
            ],
            'GT' => [
                'code' => 'GT',
                'continent' => 'NA',
                'iso3' => 'GTM',
                'capital' => 'Guatemala City',
                'name' => 'Guatemala',
                'currency_code' => 'GTQ',
            ],
            'GS' => [
                'code' => 'GS',
                'continent' => 'AN',
                'iso3' => 'SGS',
                'capital' => 'Grytviken',
                'name' => 'South Georgia and the South Sandwich Islands',
                'currency_code' => 'GBP',
            ],
            'GR' => [
                'code' => 'GR',
                'continent' => 'EU',
                'iso3' => 'GRC',
                'capital' => 'Athens',
                'name' => 'Greece',
                'currency_code' => 'EUR',
            ],
            'GQ' => [
                'code' => 'GQ',
                'continent' => 'AF',
                'iso3' => 'GNQ',
                'capital' => 'Malabo',
                'name' => 'Equatorial Guinea',
                'currency_code' => 'XAF',
            ],
            'GP' => [
                'code' => 'GP',
                'continent' => 'NA',
                'iso3' => 'GLP',
                'capital' => 'Basse-Terre',
                'name' => 'Guadeloupe',
                'currency_code' => 'EUR',
            ],
            'JP' => [
                'code' => 'JP',
                'continent' => 'AS',
                'iso3' => 'JPN',
                'capital' => 'Tokyo',
                'name' => 'Japan',
                'currency_code' => 'JPY',
            ],
            'GY' => [
                'code' => 'GY',
                'continent' => 'SA',
                'iso3' => 'GUY',
                'capital' => 'Georgetown',
                'name' => 'Guyana',
                'currency_code' => 'GYD',
            ],
            'GG' => [
                'code' => 'GG',
                'continent' => 'EU',
                'iso3' => 'GGY',
                'capital' => 'St Peter Port',
                'name' => 'Guernsey',
                'currency_code' => 'GBP',
            ],
            'GF' => [
                'code' => 'GF',
                'continent' => 'SA',
                'iso3' => 'GUF',
                'capital' => 'Cayenne',
                'name' => 'French Guiana',
                'currency_code' => 'EUR',
            ],
            'GE' => [
                'code' => 'GE',
                'continent' => 'AS',
                'iso3' => 'GEO',
                'capital' => 'Tbilisi',
                'name' => 'Georgia',
                'currency_code' => 'GEL',
            ],
            'GD' => [
                'code' => 'GD',
                'continent' => 'NA',
                'iso3' => 'GRD',
                'capital' => 'St. George\'s',
                'name' => 'Grenada',
                'currency_code' => 'XCD',
            ],
            'GB' => [
                'code' => 'GB',
                'continent' => 'EU',
                'iso3' => 'GBR',
                'capital' => 'London',
                'name' => 'United Kingdom',
                'currency_code' => 'GBP',
            ],
            'GA' => [
                'code' => 'GA',
                'continent' => 'AF',
                'iso3' => 'GAB',
                'capital' => 'Libreville',
                'name' => 'Gabon',
                'currency_code' => 'XAF',
            ],
            'SV' => [
                'code' => 'SV',
                'continent' => 'NA',
                'iso3' => 'SLV',
                'capital' => 'San Salvador',
                'name' => 'El Salvador',
                'currency_code' => 'USD',
            ],
            'GN' => [
                'code' => 'GN',
                'continent' => 'AF',
                'iso3' => 'GIN',
                'capital' => 'Conakry',
                'name' => 'Guinea',
                'currency_code' => 'GNF',
            ],
            'GM' => [
                'code' => 'GM',
                'continent' => 'AF',
                'iso3' => 'GMB',
                'capital' => 'Banjul',
                'name' => 'Gambia',
                'currency_code' => 'GMD',
            ],
            'GL' => [
                'code' => 'GL',
                'continent' => 'NA',
                'iso3' => 'GRL',
                'capital' => 'Nuuk',
                'name' => 'Greenland',
                'currency_code' => 'DKK',
            ],
            'GI' => [
                'code' => 'GI',
                'continent' => 'EU',
                'iso3' => 'GIB',
                'capital' => 'Gibraltar',
                'name' => 'Gibraltar',
                'currency_code' => 'GIP',
            ],
            'GH' => [
                'code' => 'GH',
                'continent' => 'AF',
                'iso3' => 'GHA',
                'capital' => 'Accra',
                'name' => 'Ghana',
                'currency_code' => 'GHS',
            ],
            'OM' => [
                'code' => 'OM',
                'continent' => 'AS',
                'iso3' => 'OMN',
                'capital' => 'Muscat',
                'name' => 'Oman',
                'currency_code' => 'OMR',
            ],
            'TN' => [
                'code' => 'TN',
                'continent' => 'AF',
                'iso3' => 'TUN',
                'capital' => 'Tunis',
                'name' => 'Tunisia',
                'currency_code' => 'TND',
            ],
            'JO' => [
                'code' => 'JO',
                'continent' => 'AS',
                'iso3' => 'JOR',
                'capital' => 'Amman',
                'name' => 'Jordan',
                'currency_code' => 'JOD',
            ],
            'HR' => [
                'code' => 'HR',
                'continent' => 'EU',
                'iso3' => 'HRV',
                'capital' => 'Zagreb',
                'name' => 'Croatia',
                'currency_code' => 'HRK',
            ],
            'HT' => [
                'code' => 'HT',
                'continent' => 'NA',
                'iso3' => 'HTI',
                'capital' => 'Port-au-Prince',
                'name' => 'Haiti',
                'currency_code' => 'HTG',
            ],
            'HU' => [
                'code' => 'HU',
                'continent' => 'EU',
                'iso3' => 'HUN',
                'capital' => 'Budapest',
                'name' => 'Hungary',
                'currency_code' => 'HUF',
            ],
            'HK' => [
                'code' => 'HK',
                'continent' => 'AS',
                'iso3' => 'HKG',
                'capital' => 'Hong Kong',
                'name' => 'Hong Kong',
                'currency_code' => 'HKD',
            ],
            'HN' => [
                'code' => 'HN',
                'continent' => 'NA',
                'iso3' => 'HND',
                'capital' => 'Tegucigalpa',
                'name' => 'Honduras',
                'currency_code' => 'HNL',
            ],
            'HM' => [
                'code' => 'HM',
                'continent' => 'AN',
                'iso3' => 'HMD',
                'capital' => null,
                'name' => 'Heard Island and McDonald Islands',
                'currency_code' => 'AUD',
            ],
            'VE' => [
                'code' => 'VE',
                'continent' => 'SA',
                'iso3' => 'VEN',
                'capital' => 'Caracas',
                'name' => 'Venezuela',
                'currency_code' => 'VEF',
            ],
            'PR' => [
                'code' => 'PR',
                'continent' => 'NA',
                'iso3' => 'PRI',
                'capital' => 'San Juan',
                'name' => 'Puerto Rico',
                'currency_code' => 'USD',
            ],
            'PS' => [
                'code' => 'PS',
                'continent' => 'AS',
                'iso3' => 'PSE',
                'capital' => 'East Jerusalem',
                'name' => 'Palestinian Territory',
                'currency_code' => 'ILS',
            ],
            'PW' => [
                'code' => 'PW',
                'continent' => 'OC',
                'iso3' => 'PLW',
                'capital' => 'Melekeok',
                'name' => 'Palau',
                'currency_code' => 'USD',
            ],
            'PT' => [
                'code' => 'PT',
                'continent' => 'EU',
                'iso3' => 'PRT',
                'capital' => 'Lisbon',
                'name' => 'Portugal',
                'currency_code' => 'EUR',
            ],
            'SJ' => [
                'code' => 'SJ',
                'continent' => 'EU',
                'iso3' => 'SJM',
                'capital' => 'Longyearbyen',
                'name' => 'Svalbard and Jan Mayen',
                'currency_code' => 'NOK',
            ],
            'PY' => [
                'code' => 'PY',
                'continent' => 'SA',
                'iso3' => 'PRY',
                'capital' => 'Asuncion',
                'name' => 'Paraguay',
                'currency_code' => 'PYG',
            ],
            'IQ' => [
                'code' => 'IQ',
                'continent' => 'AS',
                'iso3' => 'IRQ',
                'capital' => 'Baghdad',
                'name' => 'Iraq',
                'currency_code' => 'IQD',
            ],
            'PA' => [
                'code' => 'PA',
                'continent' => 'NA',
                'iso3' => 'PAN',
                'capital' => 'Panama City',
                'name' => 'Panama',
                'currency_code' => 'PAB',
            ],
            'PF' => [
                'code' => 'PF',
                'continent' => 'OC',
                'iso3' => 'PYF',
                'capital' => 'Papeete',
                'name' => 'French Polynesia',
                'currency_code' => 'XPF',
            ],
            'PG' => [
                'code' => 'PG',
                'continent' => 'OC',
                'iso3' => 'PNG',
                'capital' => 'Port Moresby',
                'name' => 'Papua New Guinea',
                'currency_code' => 'PGK',
            ],
            'PE' => [
                'code' => 'PE',
                'continent' => 'SA',
                'iso3' => 'PER',
                'capital' => 'Lima',
                'name' => 'Peru',
                'currency_code' => 'PEN',
            ],
            'PK' => [
                'code' => 'PK',
                'continent' => 'AS',
                'iso3' => 'PAK',
                'capital' => 'Islamabad',
                'name' => 'Pakistan',
                'currency_code' => 'PKR',
            ],
            'PH' => [
                'code' => 'PH',
                'continent' => 'AS',
                'iso3' => 'PHL',
                'capital' => 'Manila',
                'name' => 'Philippines',
                'currency_code' => 'PHP',
            ],
            'PN' => [
                'code' => 'PN',
                'continent' => 'OC',
                'iso3' => 'PCN',
                'capital' => 'Adamstown',
                'name' => 'Pitcairn',
                'currency_code' => 'NZD',
            ],
            'PL' => [
                'code' => 'PL',
                'continent' => 'EU',
                'iso3' => 'POL',
                'capital' => 'Warsaw',
                'name' => 'Poland',
                'currency_code' => 'PLN',
            ],
            'PM' => [
                'code' => 'PM',
                'continent' => 'NA',
                'iso3' => 'SPM',
                'capital' => 'Saint-Pierre',
                'name' => 'Saint Pierre and Miquelon',
                'currency_code' => 'EUR',
            ],
            'ZM' => [
                'code' => 'ZM',
                'continent' => 'AF',
                'iso3' => 'ZMB',
                'capital' => 'Lusaka',
                'name' => 'Zambia',
                'currency_code' => 'ZMK',
            ],
            'EH' => [
                'code' => 'EH',
                'continent' => 'AF',
                'iso3' => 'ESH',
                'capital' => 'El-Aaiun',
                'name' => 'Western Sahara',
                'currency_code' => 'MAD',
            ],
            'EE' => [
                'code' => 'EE',
                'continent' => 'EU',
                'iso3' => 'EST',
                'capital' => 'Tallinn',
                'name' => 'Estonia',
                'currency_code' => 'EUR',
            ],
            'EG' => [
                'code' => 'EG',
                'continent' => 'AF',
                'iso3' => 'EGY',
                'capital' => 'Cairo',
                'name' => 'Egypt',
                'currency_code' => 'EGP',
            ],
            'ZA' => [
                'code' => 'ZA',
                'continent' => 'AF',
                'iso3' => 'ZAF',
                'capital' => 'Pretoria',
                'name' => 'South Africa',
                'currency_code' => 'ZAR',
            ],
            'EC' => [
                'code' => 'EC',
                'continent' => 'SA',
                'iso3' => 'ECU',
                'capital' => 'Quito',
                'name' => 'Ecuador',
                'currency_code' => 'USD',
            ],
            'IT' => [
                'code' => 'IT',
                'continent' => 'EU',
                'iso3' => 'ITA',
                'capital' => 'Rome',
                'name' => 'Italy',
                'currency_code' => 'EUR',
            ],
            'VN' => [
                'code' => 'VN',
                'continent' => 'AS',
                'iso3' => 'VNM',
                'capital' => 'Hanoi',
                'name' => 'Vietnam',
                'currency_code' => 'VND',
            ],
            'SB' => [
                'code' => 'SB',
                'continent' => 'OC',
                'iso3' => 'SLB',
                'capital' => 'Honiara',
                'name' => 'Solomon Islands',
                'currency_code' => 'SBD',
            ],
            'ET' => [
                'code' => 'ET',
                'continent' => 'AF',
                'iso3' => 'ETH',
                'capital' => 'Addis Ababa',
                'name' => 'Ethiopia',
                'currency_code' => 'ETB',
            ],
            'SO' => [
                'code' => 'SO',
                'continent' => 'AF',
                'iso3' => 'SOM',
                'capital' => 'Mogadishu',
                'name' => 'Somalia',
                'currency_code' => 'SOS',
            ],
            'ZW' => [
                'code' => 'ZW',
                'continent' => 'AF',
                'iso3' => 'ZWE',
                'capital' => 'Harare',
                'name' => 'Zimbabwe',
                'currency_code' => 'ZWL',
            ],
            'SA' => [
                'code' => 'SA',
                'continent' => 'AS',
                'iso3' => 'SAU',
                'capital' => 'Riyadh',
                'name' => 'Saudi Arabia',
                'currency_code' => 'SAR',
            ],
            'ES' => [
                'code' => 'ES',
                'continent' => 'EU',
                'iso3' => 'ESP',
                'capital' => 'Madrid',
                'name' => 'Spain',
                'currency_code' => 'EUR',
            ],
            'ER' => [
                'code' => 'ER',
                'continent' => 'AF',
                'iso3' => 'ERI',
                'capital' => 'Asmara',
                'name' => 'Eritrea',
                'currency_code' => 'ERN',
            ],
            'ME' => [
                'code' => 'ME',
                'continent' => 'EU',
                'iso3' => 'MNE',
                'capital' => 'Podgorica',
                'name' => 'Montenegro',
                'currency_code' => 'EUR',
            ],
            'MD' => [
                'code' => 'MD',
                'continent' => 'EU',
                'iso3' => 'MDA',
                'capital' => 'Chisinau',
                'name' => 'Moldova',
                'currency_code' => 'MDL',
            ],
            'MG' => [
                'code' => 'MG',
                'continent' => 'AF',
                'iso3' => 'MDG',
                'capital' => 'Antananarivo',
                'name' => 'Madagascar',
                'currency_code' => 'MGA',
            ],
            'MF' => [
                'code' => 'MF',
                'continent' => 'NA',
                'iso3' => 'MAF',
                'capital' => 'Marigot',
                'name' => 'Saint Martin',
                'currency_code' => 'EUR',
            ],
            'MA' => [
                'code' => 'MA',
                'continent' => 'AF',
                'iso3' => 'MAR',
                'capital' => 'Rabat',
                'name' => 'Morocco',
                'currency_code' => 'MAD',
            ],
            'MC' => [
                'code' => 'MC',
                'continent' => 'EU',
                'iso3' => 'MCO',
                'capital' => 'Monaco',
                'name' => 'Monaco',
                'currency_code' => 'EUR',
            ],
            'UZ' => [
                'code' => 'UZ',
                'continent' => 'AS',
                'iso3' => 'UZB',
                'capital' => 'Tashkent',
                'name' => 'Uzbekistan',
                'currency_code' => 'UZS',
            ],
            'MM' => [
                'code' => 'MM',
                'continent' => 'AS',
                'iso3' => 'MMR',
                'capital' => 'Nay Pyi Taw',
                'name' => 'Myanmar',
                'currency_code' => 'MMK',
            ],
            'ML' => [
                'code' => 'ML',
                'continent' => 'AF',
                'iso3' => 'MLI',
                'capital' => 'Bamako',
                'name' => 'Mali',
                'currency_code' => 'XOF',
            ],
            'MO' => [
                'code' => 'MO',
                'continent' => 'AS',
                'iso3' => 'MAC',
                'capital' => 'Macao',
                'name' => 'Macao',
                'currency_code' => 'MOP',
            ],
            'MN' => [
                'code' => 'MN',
                'continent' => 'AS',
                'iso3' => 'MNG',
                'capital' => 'Ulan Bator',
                'name' => 'Mongolia',
                'currency_code' => 'MNT',
            ],
            'MH' => [
                'code' => 'MH',
                'continent' => 'OC',
                'iso3' => 'MHL',
                'capital' => 'Majuro',
                'name' => 'Marshall Islands',
                'currency_code' => 'USD',
            ],
            'MK' => [
                'code' => 'MK',
                'continent' => 'EU',
                'iso3' => 'MKD',
                'capital' => 'Skopje',
                'name' => 'Macedonia',
                'currency_code' => 'MKD',
            ],
            'MU' => [
                'code' => 'MU',
                'continent' => 'AF',
                'iso3' => 'MUS',
                'capital' => 'Port Louis',
                'name' => 'Mauritius',
                'currency_code' => 'MUR',
            ],
            'MT' => [
                'code' => 'MT',
                'continent' => 'EU',
                'iso3' => 'MLT',
                'capital' => 'Valletta',
                'name' => 'Malta',
                'currency_code' => 'EUR',
            ],
            'MW' => [
                'code' => 'MW',
                'continent' => 'AF',
                'iso3' => 'MWI',
                'capital' => 'Lilongwe',
                'name' => 'Malawi',
                'currency_code' => 'MWK',
            ],
            'MV' => [
                'code' => 'MV',
                'continent' => 'AS',
                'iso3' => 'MDV',
                'capital' => 'Male',
                'name' => 'Maldives',
                'currency_code' => 'MVR',
            ],
            'MQ' => [
                'code' => 'MQ',
                'continent' => 'NA',
                'iso3' => 'MTQ',
                'capital' => 'Fort-de-France',
                'name' => 'Martinique',
                'currency_code' => 'EUR',
            ],
            'MP' => [
                'code' => 'MP',
                'continent' => 'OC',
                'iso3' => 'MNP',
                'capital' => 'Saipan',
                'name' => 'Northern Mariana Islands',
                'currency_code' => 'USD',
            ],
            'MS' => [
                'code' => 'MS',
                'continent' => 'NA',
                'iso3' => 'MSR',
                'capital' => 'Plymouth',
                'name' => 'Montserrat',
                'currency_code' => 'XCD',
            ],
            'MR' => [
                'code' => 'MR',
                'continent' => 'AF',
                'iso3' => 'MRT',
                'capital' => 'Nouakchott',
                'name' => 'Mauritania',
                'currency_code' => 'MRO',
            ],
            'IM' => [
                'code' => 'IM',
                'continent' => 'EU',
                'iso3' => 'IMN',
                'capital' => 'Douglas, Isle of Man',
                'name' => 'Isle of Man',
                'currency_code' => 'GBP',
            ],
            'UG' => [
                'code' => 'UG',
                'continent' => 'AF',
                'iso3' => 'UGA',
                'capital' => 'Kampala',
                'name' => 'Uganda',
                'currency_code' => 'UGX',
            ],
            'TZ' => [
                'code' => 'TZ',
                'continent' => 'AF',
                'iso3' => 'TZA',
                'capital' => 'Dodoma',
                'name' => 'Tanzania',
                'currency_code' => 'TZS',
            ],
            'MY' => [
                'code' => 'MY',
                'continent' => 'AS',
                'iso3' => 'MYS',
                'capital' => 'Kuala Lumpur',
                'name' => 'Malaysia',
                'currency_code' => 'MYR',
            ],
            'MX' => [
                'code' => 'MX',
                'continent' => 'NA',
                'iso3' => 'MEX',
                'capital' => 'Mexico City',
                'name' => 'Mexico',
                'currency_code' => 'MXN',
            ],
            'IL' => [
                'code' => 'IL',
                'continent' => 'AS',
                'iso3' => 'ISR',
                'capital' => 'Jerusalem',
                'name' => 'Israel',
                'currency_code' => 'ILS',
            ],
            'FR' => [
                'code' => 'FR',
                'continent' => 'EU',
                'iso3' => 'FRA',
                'capital' => 'Paris',
                'name' => 'France',
                'currency_code' => 'EUR',
            ],
            'IO' => [
                'code' => 'IO',
                'continent' => 'AS',
                'iso3' => 'IOT',
                'capital' => 'Diego Garcia',
                'name' => 'British Indian Ocean Territory',
                'currency_code' => 'USD',
            ],
            'SH' => [
                'code' => 'SH',
                'continent' => 'AF',
                'iso3' => 'SHN',
                'capital' => 'Jamestown',
                'name' => 'Saint Helena',
                'currency_code' => 'SHP',
            ],
            'FI' => [
                'code' => 'FI',
                'continent' => 'EU',
                'iso3' => 'FIN',
                'capital' => 'Helsinki',
                'name' => 'Finland',
                'currency_code' => 'EUR',
            ],
            'FJ' => [
                'code' => 'FJ',
                'continent' => 'OC',
                'iso3' => 'FJI',
                'capital' => 'Suva',
                'name' => 'Fiji',
                'currency_code' => 'FJD',
            ],
            'FK' => [
                'code' => 'FK',
                'continent' => 'SA',
                'iso3' => 'FLK',
                'capital' => 'Stanley',
                'name' => 'Falkland Islands',
                'currency_code' => 'FKP',
            ],
            'FM' => [
                'code' => 'FM',
                'continent' => 'OC',
                'iso3' => 'FSM',
                'capital' => 'Palikir',
                'name' => 'Micronesia',
                'currency_code' => 'USD',
            ],
            'FO' => [
                'code' => 'FO',
                'continent' => 'EU',
                'iso3' => 'FRO',
                'capital' => 'Torshavn',
                'name' => 'Faroe Islands',
                'currency_code' => 'DKK',
            ],
            'NI' => [
                'code' => 'NI',
                'continent' => 'NA',
                'iso3' => 'NIC',
                'capital' => 'Managua',
                'name' => 'Nicaragua',
                'currency_code' => 'NIO',
            ],
            'NL' => [
                'code' => 'NL',
                'continent' => 'EU',
                'iso3' => 'NLD',
                'capital' => 'Amsterdam',
                'name' => 'Netherlands',
                'currency_code' => 'EUR',
            ],
            'NO' => [
                'code' => 'NO',
                'continent' => 'EU',
                'iso3' => 'NOR',
                'capital' => 'Oslo',
                'name' => 'Norway',
                'currency_code' => 'NOK',
            ],
            'NA' => [
                'code' => 'NA',
                'continent' => 'AF',
                'iso3' => 'NAM',
                'capital' => 'Windhoek',
                'name' => 'Namibia',
                'currency_code' => 'NAD',
            ],
            'VU' => [
                'code' => 'VU',
                'continent' => 'OC',
                'iso3' => 'VUT',
                'capital' => 'Port Vila',
                'name' => 'Vanuatu',
                'currency_code' => 'VUV',
            ],
            'NC' => [
                'code' => 'NC',
                'continent' => 'OC',
                'iso3' => 'NCL',
                'capital' => 'Noumea',
                'name' => 'New Caledonia',
                'currency_code' => 'XPF',
            ],
            'NE' => [
                'code' => 'NE',
                'continent' => 'AF',
                'iso3' => 'NER',
                'capital' => 'Niamey',
                'name' => 'Niger',
                'currency_code' => 'XOF',
            ],
            'NF' => [
                'code' => 'NF',
                'continent' => 'OC',
                'iso3' => 'NFK',
                'capital' => 'Kingston',
                'name' => 'Norfolk Island',
                'currency_code' => 'AUD',
            ],
            'NG' => [
                'code' => 'NG',
                'continent' => 'AF',
                'iso3' => 'NGA',
                'capital' => 'Abuja',
                'name' => 'Nigeria',
                'currency_code' => 'NGN',
            ],
            'NZ' => [
                'code' => 'NZ',
                'continent' => 'OC',
                'iso3' => 'NZL',
                'capital' => 'Wellington',
                'name' => 'New Zealand',
                'currency_code' => 'NZD',
            ],
            'NP' => [
                'code' => 'NP',
                'continent' => 'AS',
                'iso3' => 'NPL',
                'capital' => 'Kathmandu',
                'name' => 'Nepal',
                'currency_code' => 'NPR',
            ],
            'NR' => [
                'code' => 'NR',
                'continent' => 'OC',
                'iso3' => 'NRU',
                'capital' => 'Yaren',
                'name' => 'Nauru',
                'currency_code' => 'AUD',
            ],
            'NU' => [
                'code' => 'NU',
                'continent' => 'OC',
                'iso3' => 'NIU',
                'capital' => 'Alofi',
                'name' => 'Niue',
                'currency_code' => 'NZD',
            ],
            'CK' => [
                'code' => 'CK',
                'continent' => 'OC',
                'iso3' => 'COK',
                'capital' => 'Avarua',
                'name' => 'Cook Islands',
                'currency_code' => 'NZD',
            ],
            'XK' => [
                'code' => 'XK',
                'continent' => 'EU',
                'iso3' => 'XKX',
                'capital' => 'Pristina',
                'name' => 'Kosovo',
                'currency_code' => 'EUR',
            ],
            'CI' => [
                'code' => 'CI',
                'continent' => 'AF',
                'iso3' => 'CIV',
                'capital' => 'Yamoussoukro',
                'name' => 'Ivory Coast',
                'currency_code' => 'XOF',
            ],
            'CH' => [
                'code' => 'CH',
                'continent' => 'EU',
                'iso3' => 'CHE',
                'capital' => 'Berne',
                'name' => 'Switzerland',
                'currency_code' => 'CHF',
            ],
            'CO' => [
                'code' => 'CO',
                'continent' => 'SA',
                'iso3' => 'COL',
                'capital' => 'Bogota',
                'name' => 'Colombia',
                'currency_code' => 'COP',
            ],
            'CN' => [
                'code' => 'CN',
                'continent' => 'AS',
                'iso3' => 'CHN',
                'capital' => 'Beijing',
                'name' => 'China',
                'currency_code' => 'CNY',
            ],
            'CM' => [
                'code' => 'CM',
                'continent' => 'AF',
                'iso3' => 'CMR',
                'capital' => 'Yaounde',
                'name' => 'Cameroon',
                'currency_code' => 'XAF',
            ],
            'CL' => [
                'code' => 'CL',
                'continent' => 'SA',
                'iso3' => 'CHL',
                'capital' => 'Santiago',
                'name' => 'Chile',
                'currency_code' => 'CLP',
            ],
            'CC' => [
                'code' => 'CC',
                'continent' => 'AS',
                'iso3' => 'CCK',
                'capital' => 'West Island',
                'name' => 'Cocos Islands',
                'currency_code' => 'AUD',
            ],
            'CA' => [
                'code' => 'CA',
                'continent' => 'NA',
                'iso3' => 'CAN',
                'capital' => 'Ottawa',
                'name' => 'Canada',
                'currency_code' => 'CAD',
            ],
            'CG' => [
                'code' => 'CG',
                'continent' => 'AF',
                'iso3' => 'COG',
                'capital' => 'Brazzaville',
                'name' => 'Republic of the Congo',
                'currency_code' => 'XAF',
            ],
            'CF' => [
                'code' => 'CF',
                'continent' => 'AF',
                'iso3' => 'CAF',
                'capital' => 'Bangui',
                'name' => 'Central African Republic',
                'currency_code' => 'XAF',
            ],
            'CD' => [
                'code' => 'CD',
                'continent' => 'AF',
                'iso3' => 'COD',
                'capital' => 'Kinshasa',
                'name' => 'Democratic Republic of the Congo',
                'currency_code' => 'CDF',
            ],
            'CZ' => [
                'code' => 'CZ',
                'continent' => 'EU',
                'iso3' => 'CZE',
                'capital' => 'Prague',
                'name' => 'Czech Republic',
                'currency_code' => 'CZK',
            ],
            'CY' => [
                'code' => 'CY',
                'continent' => 'EU',
                'iso3' => 'CYP',
                'capital' => 'Nicosia',
                'name' => 'Cyprus',
                'currency_code' => 'EUR',
            ],
            'CX' => [
                'code' => 'CX',
                'continent' => 'AS',
                'iso3' => 'CXR',
                'capital' => 'Flying Fish Cove',
                'name' => 'Christmas Island',
                'currency_code' => 'AUD',
            ],
            'CR' => [
                'code' => 'CR',
                'continent' => 'NA',
                'iso3' => 'CRI',
                'capital' => 'San Jose',
                'name' => 'Costa Rica',
                'currency_code' => 'CRC',
            ],
            'CW' => [
                'code' => 'CW',
                'continent' => 'NA',
                'iso3' => 'CUW',
                'capital' => ' Willemstad',
                'name' => 'Curacao',
                'currency_code' => 'ANG',
            ],
            'CV' => [
                'code' => 'CV',
                'continent' => 'AF',
                'iso3' => 'CPV',
                'capital' => 'Praia',
                'name' => 'Cape Verde',
                'currency_code' => 'CVE',
            ],
            'CU' => [
                'code' => 'CU',
                'continent' => 'NA',
                'iso3' => 'CUB',
                'capital' => 'Havana',
                'name' => 'Cuba',
                'currency_code' => 'CUP',
            ],
            'SZ' => [
                'code' => 'SZ',
                'continent' => 'AF',
                'iso3' => 'SWZ',
                'capital' => 'Mbabane',
                'name' => 'Swaziland',
                'currency_code' => 'SZL',
            ],
            'SY' => [
                'code' => 'SY',
                'continent' => 'AS',
                'iso3' => 'SYR',
                'capital' => 'Damascus',
                'name' => 'Syria',
                'currency_code' => 'SYP',
            ],
            'SX' => [
                'code' => 'SX',
                'continent' => 'NA',
                'iso3' => 'SXM',
                'capital' => 'Philipsburg',
                'name' => 'Sint Maarten',
                'currency_code' => 'ANG',
            ],
            'KG' => [
                'code' => 'KG',
                'continent' => 'AS',
                'iso3' => 'KGZ',
                'capital' => 'Bishkek',
                'name' => 'Kyrgyzstan',
                'currency_code' => 'KGS',
            ],
            'KE' => [
                'code' => 'KE',
                'continent' => 'AF',
                'iso3' => 'KEN',
                'capital' => 'Nairobi',
                'name' => 'Kenya',
                'currency_code' => 'KES',
            ],
            'SS' => [
                'code' => 'SS',
                'continent' => 'AF',
                'iso3' => 'SSD',
                'capital' => 'Juba',
                'name' => 'South Sudan',
                'currency_code' => 'SSP',
            ],
            'SR' => [
                'code' => 'SR',
                'continent' => 'SA',
                'iso3' => 'SUR',
                'capital' => 'Paramaribo',
                'name' => 'Suriname',
                'currency_code' => 'SRD',
            ],
            'KI' => [
                'code' => 'KI',
                'continent' => 'OC',
                'iso3' => 'KIR',
                'capital' => 'Tarawa',
                'name' => 'Kiribati',
                'currency_code' => 'AUD',
            ],
            'KH' => [
                'code' => 'KH',
                'continent' => 'AS',
                'iso3' => 'KHM',
                'capital' => 'Phnom Penh',
                'name' => 'Cambodia',
                'currency_code' => 'KHR',
            ],
            'KN' => [
                'code' => 'KN',
                'continent' => 'NA',
                'iso3' => 'KNA',
                'capital' => 'Basseterre',
                'name' => 'Saint Kitts and Nevis',
                'currency_code' => 'XCD',
            ],
            'KM' => [
                'code' => 'KM',
                'continent' => 'AF',
                'iso3' => 'COM',
                'capital' => 'Moroni',
                'name' => 'Comoros',
                'currency_code' => 'KMF',
            ],
            'ST' => [
                'code' => 'ST',
                'continent' => 'AF',
                'iso3' => 'STP',
                'capital' => 'Sao Tome',
                'name' => 'Sao Tome and Principe',
                'currency_code' => 'STD',
            ],
            'SK' => [
                'code' => 'SK',
                'continent' => 'EU',
                'iso3' => 'SVK',
                'capital' => 'Bratislava',
                'name' => 'Slovakia',
                'currency_code' => 'EUR',
            ],
            'KR' => [
                'code' => 'KR',
                'continent' => 'AS',
                'iso3' => 'KOR',
                'capital' => 'Seoul',
                'name' => 'South Korea',
                'currency_code' => 'KRW',
            ],
            'SI' => [
                'code' => 'SI',
                'continent' => 'EU',
                'iso3' => 'SVN',
                'capital' => 'Ljubljana',
                'name' => 'Slovenia',
                'currency_code' => 'EUR',
            ],
            'KP' => [
                'code' => 'KP',
                'continent' => 'AS',
                'iso3' => 'PRK',
                'capital' => 'Pyongyang',
                'name' => 'North Korea',
                'currency_code' => 'KPW',
            ],
            'KW' => [
                'code' => 'KW',
                'continent' => 'AS',
                'iso3' => 'KWT',
                'capital' => 'Kuwait City',
                'name' => 'Kuwait',
                'currency_code' => 'KWD',
            ],
            'SN' => [
                'code' => 'SN',
                'continent' => 'AF',
                'iso3' => 'SEN',
                'capital' => 'Dakar',
                'name' => 'Senegal',
                'currency_code' => 'XOF',
            ],
            'SM' => [
                'code' => 'SM',
                'continent' => 'EU',
                'iso3' => 'SMR',
                'capital' => 'San Marino',
                'name' => 'San Marino',
                'currency_code' => 'EUR',
            ],
            'SL' => [
                'code' => 'SL',
                'continent' => 'AF',
                'iso3' => 'SLE',
                'capital' => 'Freetown',
                'name' => 'Sierra Leone',
                'currency_code' => 'SLL',
            ],
            'SC' => [
                'code' => 'SC',
                'continent' => 'AF',
                'iso3' => 'SYC',
                'capital' => 'Victoria',
                'name' => 'Seychelles',
                'currency_code' => 'SCR',
            ],
            'KZ' => [
                'code' => 'KZ',
                'continent' => 'AS',
                'iso3' => 'KAZ',
                'capital' => 'Astana',
                'name' => 'Kazakhstan',
                'currency_code' => 'KZT',
            ],
            'KY' => [
                'code' => 'KY',
                'continent' => 'NA',
                'iso3' => 'CYM',
                'capital' => 'George Town',
                'name' => 'Cayman Islands',
                'currency_code' => 'KYD',
            ],
            'SG' => [
                'code' => 'SG',
                'continent' => 'AS',
                'iso3' => 'SGP',
                'capital' => 'Singapur',
                'name' => 'Singapore',
                'currency_code' => 'SGD',
            ],
            'SE' => [
                'code' => 'SE',
                'continent' => 'EU',
                'iso3' => 'SWE',
                'capital' => 'Stockholm',
                'name' => 'Sweden',
                'currency_code' => 'SEK',
            ],
            'SD' => [
                'code' => 'SD',
                'continent' => 'AF',
                'iso3' => 'SDN',
                'capital' => 'Khartoum',
                'name' => 'Sudan',
                'currency_code' => 'SDG',
            ],
            'DO' => [
                'code' => 'DO',
                'continent' => 'NA',
                'iso3' => 'DOM',
                'capital' => 'Santo Domingo',
                'name' => 'Dominican Republic',
                'currency_code' => 'DOP',
            ],
            'DM' => [
                'code' => 'DM',
                'continent' => 'NA',
                'iso3' => 'DMA',
                'capital' => 'Roseau',
                'name' => 'Dominica',
                'currency_code' => 'XCD',
            ],
            'DJ' => [
                'code' => 'DJ',
                'continent' => 'AF',
                'iso3' => 'DJI',
                'capital' => 'Djibouti',
                'name' => 'Djibouti',
                'currency_code' => 'DJF',
            ],
            'DK' => [
                'code' => 'DK',
                'continent' => 'EU',
                'iso3' => 'DNK',
                'capital' => 'Copenhagen',
                'name' => 'Denmark',
                'currency_code' => 'DKK',
            ],
            'VG' => [
                'code' => 'VG',
                'continent' => 'NA',
                'iso3' => 'VGB',
                'capital' => 'Road Town',
                'name' => 'British Virgin Islands',
                'currency_code' => 'USD',
            ],
            'DE' => [
                'code' => 'DE',
                'continent' => 'EU',
                'iso3' => 'DEU',
                'capital' => 'Berlin',
                'name' => 'Germany',
                'currency_code' => 'EUR',
            ],
            'YE' => [
                'code' => 'YE',
                'continent' => 'AS',
                'iso3' => 'YEM',
                'capital' => 'Sanaa',
                'name' => 'Yemen',
                'currency_code' => 'YER',
            ],
            'DZ' => [
                'code' => 'DZ',
                'continent' => 'AF',
                'iso3' => 'DZA',
                'capital' => 'Algiers',
                'name' => 'Algeria',
                'currency_code' => 'DZD',
            ],
            'US' => [
                'code' => 'US',
                'continent' => 'NA',
                'iso3' => 'USA',
                'capital' => 'Washington',
                'name' => 'United States',
                'currency_code' => 'USD',
            ],
            'UY' => [
                'code' => 'UY',
                'continent' => 'SA',
                'iso3' => 'URY',
                'capital' => 'Montevideo',
                'name' => 'Uruguay',
                'currency_code' => 'UYU',
            ],
            'YT' => [
                'code' => 'YT',
                'continent' => 'AF',
                'iso3' => 'MYT',
                'capital' => 'Mamoudzou',
                'name' => 'Mayotte',
                'currency_code' => 'EUR',
            ],
            'UM' => [
                'code' => 'UM',
                'continent' => 'OC',
                'iso3' => 'UMI',
                'capital' => null,
                'name' => 'United States Minor Outlying Islands',
                'currency_code' => 'USD',
            ],
            'LB' => [
                'code' => 'LB',
                'continent' => 'AS',
                'iso3' => 'LBN',
                'capital' => 'Beirut',
                'name' => 'Lebanon',
                'currency_code' => 'LBP',
            ],
            'LC' => [
                'code' => 'LC',
                'continent' => 'NA',
                'iso3' => 'LCA',
                'capital' => 'Castries',
                'name' => 'Saint Lucia',
                'currency_code' => 'XCD',
            ],
            'LA' => [
                'code' => 'LA',
                'continent' => 'AS',
                'iso3' => 'LAO',
                'capital' => 'Vientiane',
                'name' => 'Laos',
                'currency_code' => 'LAK',
            ],
            'TV' => [
                'code' => 'TV',
                'continent' => 'OC',
                'iso3' => 'TUV',
                'capital' => 'Funafuti',
                'name' => 'Tuvalu',
                'currency_code' => 'AUD',
            ],
            'TW' => [
                'code' => 'TW',
                'continent' => 'AS',
                'iso3' => 'TWN',
                'capital' => 'Taipei',
                'name' => 'Taiwan',
                'currency_code' => 'TWD',
            ],
            'TT' => [
                'code' => 'TT',
                'continent' => 'NA',
                'iso3' => 'TTO',
                'capital' => 'Port of Spain',
                'name' => 'Trinidad and Tobago',
                'currency_code' => 'TTD',
            ],
            'TR' => [
                'code' => 'TR',
                'continent' => 'AS',
                'iso3' => 'TUR',
                'capital' => 'Ankara',
                'name' => 'Turkey',
                'currency_code' => 'TRY',
            ],
            'LK' => [
                'code' => 'LK',
                'continent' => 'AS',
                'iso3' => 'LKA',
                'capital' => 'Colombo',
                'name' => 'Sri Lanka',
                'currency_code' => 'LKR',
            ],
            'LI' => [
                'code' => 'LI',
                'continent' => 'EU',
                'iso3' => 'LIE',
                'capital' => 'Vaduz',
                'name' => 'Liechtenstein',
                'currency_code' => 'CHF',
            ],
            'LV' => [
                'code' => 'LV',
                'continent' => 'EU',
                'iso3' => 'LVA',
                'capital' => 'Riga',
                'name' => 'Latvia',
                'currency_code' => 'EUR',
            ],
            'TO' => [
                'code' => 'TO',
                'continent' => 'OC',
                'iso3' => 'TON',
                'capital' => 'Nuku\'alofa',
                'name' => 'Tonga',
                'currency_code' => 'TOP',
            ],
            'LT' => [
                'code' => 'LT',
                'continent' => 'EU',
                'iso3' => 'LTU',
                'capital' => 'Vilnius',
                'name' => 'Lithuania',
                'currency_code' => 'LTL',
            ],
            'LU' => [
                'code' => 'LU',
                'continent' => 'EU',
                'iso3' => 'LUX',
                'capital' => 'Luxembourg',
                'name' => 'Luxembourg',
                'currency_code' => 'EUR',
            ],
            'LR' => [
                'code' => 'LR',
                'continent' => 'AF',
                'iso3' => 'LBR',
                'capital' => 'Monrovia',
                'name' => 'Liberia',
                'currency_code' => 'LRD',
            ],
            'LS' => [
                'code' => 'LS',
                'continent' => 'AF',
                'iso3' => 'LSO',
                'capital' => 'Maseru',
                'name' => 'Lesotho',
                'currency_code' => 'LSL',
            ],
            'TH' => [
                'code' => 'TH',
                'continent' => 'AS',
                'iso3' => 'THA',
                'capital' => 'Bangkok',
                'name' => 'Thailand',
                'currency_code' => 'THB',
            ],
            'TF' => [
                'code' => 'TF',
                'continent' => 'AN',
                'iso3' => 'ATF',
                'capital' => 'Port-aux-Francais',
                'name' => 'French Southern Territories',
                'currency_code' => 'EUR',
            ],
            'TG' => [
                'code' => 'TG',
                'continent' => 'AF',
                'iso3' => 'TGO',
                'capital' => 'Lome',
                'name' => 'Togo',
                'currency_code' => 'XOF',
            ],
            'TD' => [
                'code' => 'TD',
                'continent' => 'AF',
                'iso3' => 'TCD',
                'capital' => 'N\'Djamena',
                'name' => 'Chad',
                'currency_code' => 'XAF',
            ],
            'TC' => [
                'code' => 'TC',
                'continent' => 'NA',
                'iso3' => 'TCA',
                'capital' => 'Cockburn Town',
                'name' => 'Turks and Caicos Islands',
                'currency_code' => 'USD',
            ],
            'LY' => [
                'code' => 'LY',
                'continent' => 'AF',
                'iso3' => 'LBY',
                'capital' => 'Tripolis',
                'name' => 'Libya',
                'currency_code' => 'LYD',
            ],
            'VA' => [
                'code' => 'VA',
                'continent' => 'EU',
                'iso3' => 'VAT',
                'capital' => 'Vatican City',
                'name' => 'Vatican',
                'currency_code' => 'EUR',
            ],
            'VC' => [
                'code' => 'VC',
                'continent' => 'NA',
                'iso3' => 'VCT',
                'capital' => 'Kingstown',
                'name' => 'Saint Vincent and the Grenadines',
                'currency_code' => 'XCD',
            ],
            'AE' => [
                'code' => 'AE',
                'continent' => 'AS',
                'iso3' => 'ARE',
                'capital' => 'Abu Dhabi',
                'name' => 'United Arab Emirates',
                'currency_code' => 'AED',
            ],
            'AD' => [
                'code' => 'AD',
                'continent' => 'EU',
                'iso3' => 'AND',
                'capital' => 'Andorra la Vella',
                'name' => 'Andorra',
                'currency_code' => 'EUR',
            ],
            'AG' => [
                'code' => 'AG',
                'continent' => 'NA',
                'iso3' => 'ATG',
                'capital' => 'St. John\'s',
                'name' => 'Antigua and Barbuda',
                'currency_code' => 'XCD',
            ],
            'AF' => [
                'code' => 'AF',
                'continent' => 'AS',
                'iso3' => 'AFG',
                'capital' => 'Kabul',
                'name' => 'Afghanistan',
                'currency_code' => 'AFN',
            ],
            'AI' => [
                'code' => 'AI',
                'continent' => 'NA',
                'iso3' => 'AIA',
                'capital' => 'The Valley',
                'name' => 'Anguilla',
                'currency_code' => 'XCD',
            ],
            'VI' => [
                'code' => 'VI',
                'continent' => 'NA',
                'iso3' => 'VIR',
                'capital' => 'Charlotte Amalie',
                'name' => 'U.S. Virgin Islands',
                'currency_code' => 'USD',
            ],
            'IS' => [
                'code' => 'IS',
                'continent' => 'EU',
                'iso3' => 'ISL',
                'capital' => 'Reykjavik',
                'name' => 'Iceland',
                'currency_code' => 'ISK',
            ],
            'IR' => [
                'code' => 'IR',
                'continent' => 'AS',
                'iso3' => 'IRN',
                'capital' => 'Tehran',
                'name' => 'Iran',
                'currency_code' => 'IRR',
            ],
            'AM' => [
                'code' => 'AM',
                'continent' => 'AS',
                'iso3' => 'ARM',
                'capital' => 'Yerevan',
                'name' => 'Armenia',
                'currency_code' => 'AMD',
            ],
            'AL' => [
                'code' => 'AL',
                'continent' => 'EU',
                'iso3' => 'ALB',
                'capital' => 'Tirana',
                'name' => 'Albania',
                'currency_code' => 'ALL',
            ],
            'AO' => [
                'code' => 'AO',
                'continent' => 'AF',
                'iso3' => 'AGO',
                'capital' => 'Luanda',
                'name' => 'Angola',
                'currency_code' => 'AOA',
            ],
            'AQ' => [
                'code' => 'AQ',
                'continent' => 'AN',
                'iso3' => 'ATA',
                'capital' => null,
                'name' => 'Antarctica',
                'currency_code' => null,
            ],
            'AS' => [
                'code' => 'AS',
                'continent' => 'OC',
                'iso3' => 'ASM',
                'capital' => 'Pago Pago',
                'name' => 'American Samoa',
                'currency_code' => 'USD',
            ],
            'AR' => [
                'code' => 'AR',
                'continent' => 'SA',
                'iso3' => 'ARG',
                'capital' => 'Buenos Aires',
                'name' => 'Argentina',
                'currency_code' => 'ARS',
            ],
            'AU' => [
                'code' => 'AU',
                'continent' => 'OC',
                'iso3' => 'AUS',
                'capital' => 'Canberra',
                'name' => 'Australia',
                'currency_code' => 'AUD',
            ],
            'AT' => [
                'code' => 'AT',
                'continent' => 'EU',
                'iso3' => 'AUT',
                'capital' => 'Vienna',
                'name' => 'Austria',
                'currency_code' => 'EUR',
            ],
            'AW' => [
                'code' => 'AW',
                'continent' => 'NA',
                'iso3' => 'ABW',
                'capital' => 'Oranjestad',
                'name' => 'Aruba',
                'currency_code' => 'AWG',
            ],
            'IN' => [
                'code' => 'IN',
                'continent' => 'AS',
                'iso3' => 'IND',
                'capital' => 'New Delhi',
                'name' => 'India',
                'currency_code' => 'INR',
            ],
            'AX' => [
                'code' => 'AX',
                'continent' => 'EU',
                'iso3' => 'ALA',
                'capital' => 'Mariehamn',
                'name' => 'Aland Islands',
                'currency_code' => 'EUR',
            ],
            'AZ' => [
                'code' => 'AZ',
                'continent' => 'AS',
                'iso3' => 'AZE',
                'capital' => 'Baku',
                'name' => 'Azerbaijan',
                'currency_code' => 'AZN',
            ],
            'IE' => [
                'code' => 'IE',
                'continent' => 'EU',
                'iso3' => 'IRL',
                'capital' => 'Dublin',
                'name' => 'Ireland',
                'currency_code' => 'EUR',
            ],
            'ID' => [
                'code' => 'ID',
                'continent' => 'AS',
                'iso3' => 'IDN',
                'capital' => 'Jakarta',
                'name' => 'Indonesia',
                'currency_code' => 'IDR',
            ],
            'UA' => [
                'code' => 'UA',
                'continent' => 'EU',
                'iso3' => 'UKR',
                'capital' => 'Kiev',
                'name' => 'Ukraine',
                'currency_code' => 'UAH',
            ],
            'QA' => [
                'code' => 'QA',
                'continent' => 'AS',
                'iso3' => 'QAT',
                'capital' => 'Doha',
                'name' => 'Qatar',
                'currency_code' => 'QAR',
            ],
            'MZ' => [
                'code' => 'MZ',
                'continent' => 'AF',
                'iso3' => 'MOZ',
                'capital' => 'Maputo',
                'name' => 'Mozambique',
                'currency_code' => 'MZN',
            ],
        ];

        $countryJson = json_decode(file_get_contents(daalder_path('storage/app/countries.json')));

        foreach ($countryJson as $country) {
            $c = $countries[$country->cca2];
            $countries[$country->cca2] = array_merge($c, [
                'native_name' => optional(Arr::first((array)$country->name->native))->common ?? $c['name'],
                'flag' => $country->flag,
                'region' => $country->region,
                'subregion' => $country->subregion,
                'lat' => Arr::first($country->latlng),
                'lng' => Arr::last($country->latlng),
                'phone' => collect($country->idd->suffixes)->map(function ($suffix) use ($country) {
                    return $country->idd->root . str_replace('X', '', $suffix);
                })->implode(','),
                'tld' => Arr::first($country->tld),
            ]);
        }

        foreach ($countries as $code => $country) {
            Country::query()->updateOrInsert(['code' => $code], $country);
        }
    }
}
